spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: demo
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass

app:
  token:
    secret: kriang
    issuer: BackendDemo